disableLastModified: true
meta:
  title: ShipEngine Connect
  description: ShipEngine Connect powers ShipStation products, including ShipStation UI and ShipStation API.
  siteUrl: https://connect.shipengine.com/
  keywords: redocly developer portal, api portal starter, api reference docs
  lang: en-US
linkChecker:
  severity: warning
  options:
    CheckExternal: false
logo:
  image: ./images/shipengine-connect-logo.svg
  altText: ShipEngine Connect
toc:
  enable: true
oasDefinitions:
  shipping: https://api.redocly.com/registry/bundle/auctane-uff/Carrier/V1/openapi.yaml?branch=master
  orders: https://api.redocly.com/registry/bundle/auctane-uff/Orders/V1/openapi.yaml?branch=master
  freight: https://api.redocly.com/registry/bundle/auctane-uff/Freight/V1/openapi.yaml?branch=master
  inventory: https://api.redocly.com/registry/bundle/auctane-uff/Inventory/V1/openapi.yaml?branch=master
  nativeRating: https://api.redocly.com/registry/bundle/auctane-uff/Native%20Rating/V1/openapi.yaml?branch=master
  fulfillmentProvider: https://api.redocly.com/registry/bundle/auctane-uff/Fulfillment%20Provider/V1/openapi.yaml?branch=master

stylesheets:
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,600,700&display=swap
  - ./main.css
#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:
  - search: true

footer:
  copyrightText: Â© ShipEngine. All rights reserved.
  columns:
    - group: Support
      items:
        - label: FAQ
          page: faq.md
        - label: Contact us
          page: contact.mdx
