name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  website:
    name: website
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node@14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: yarn lint
        working-directory: packages/website
        run: yarn lint

      - name: yarn build
        working-directory: packages/website
        run: yarn build

      - name: yarn test
        working-directory: packages/website
        run: yarn test

  libraries:
    name: ${{ matrix.dir }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        dir:
          - packages/connect
          - packages/cli
          - packages/loader
          - packages/sdk

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node@14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: yarn lint
        working-directory: ${{ matrix.dir }}
        run: yarn lint

      - name: yarn build
        working-directory: ${{ matrix.dir }}
        run: yarn build

      - name: yarn test
        working-directory: ${{ matrix.dir }}
        run: yarn test
        env:
          HOME: ./
