name: connect test

on:
  push:
    branches:
      - master
    paths:
      - "packages/connect/**"
      - ".github/workflows/connect-ci.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "packages/connect/**"
      - ".github/workflows/connect-ci.yaml"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node@14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: yarn lint
        working-directory: packages/connect
        run: yarn lint

      - name: yarn build
        working-directory: packages/connect
        run: yarn build

      - name: yarn test
        working-directory: packages/connect
        run: yarn test
        env:
          HOME: ./
