name: order-source-api CI-CD

on:
  push:
    branches:
      - master
    paths:
      - "packages/order-source-api/**"
      - ".github/workflows/order-source-api-ci-cd.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "packages/order-source-api/**"
      - ".github/workflows/order-source-api-ci-cd.yaml"

jobs:
  ci:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node@14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: yarn install
        run: yarn install --immutable --immutable-cache

      - name: yarn lint
        working-directory: packages/order-source-api
        run: yarn lint

      - name: yarn build
        working-directory: packages/order-source-api
        run: yarn build

      - name: yarn test
        working-directory: packages/order-source-api
        run: yarn test
        env:
          HOME: ./

  cd:
    if: github.ref == 'refs/heads/master'
    name: Publish to NPM
    needs: ci
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Configure git identity
        run: |
          # Configure git for commits
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14

      - id: check
        name: Check for Published Package
        run: |
          set +e
          ./scripts/check-for-published-package.js order-source-api
          echo ::set-output name=status::$?

      - if: steps.check.outputs.status == '0'
        name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - if: steps.check.outputs.status == '0'
        name: Build
        working-directory: packages/order-source-api
        run: yarn build

      - id: publish
        if: steps.check.outputs.status == '0'
        name: Publish to NPM
        run: |
          yarn publish
          echo ::set-output name=version::$(yarn run version::lookup)
        working-directory: packages/order-source-api
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - if: steps.check.outputs.status == '0'
        name: Tag Release
        working-directory: packages/order-source-api
        run: |
          yarn run clean:tags
          OLD_VERSION=$(git tag -l 'order-source-api_v*' --sort=v:refname | tail -n 1)
          yarn run version:tag
          git push --tags

          cd ${{ github.workspace }}
          git log --oneline order-source-api_v${OLD_VERSION}..order-source-api_v${{ steps.publish.outputs.version }} -- packages/order-source-api > release-changelog.txt
        env:
          NEW_VERSION: ${{ steps.publish.outputs.version }}

      - name: Create GitHub Release
        if: steps.check.outputs.status == '0'
        uses: actions/github-script@v3
        with:
          script: |
            const { readFile } = require('fs');
            let body = '';
            readFile('${{ github.workspace }}/release-changelog.txt', 'utf8', (err, data) => {
              if (!err) body = data;
              try {
                github.repos.createRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: 'order-source-api_v${{ steps.publish.outputs.version }}',
                  body
                });
              } catch (err) {
                core.warning(`Unable to create release: ${err}`);
              }
            });
